### ISSUE TITLE
Add Providers for simplification

### ISSUE THREAD

**Issue by FiberJW** [testshallpass/react-native-dropdownalert#30]
For my app, I wrote a little provider + connect HOC so that I don't have to duplicate my code everywhere. It works really well with this lib and would be a good feature to have. Here's the code for my provider https://gist.github.com/datwheat/8149b84df7479925e857ea40d4739f68

**Comment by devBrian** [comment]
I have a few questions. 

1. How do you include the provider with another screen/component?
2. Like how do you call it?
3. I am not too familiar with HOC what's that concept about?

**Comment by datwheat** [comment]
The provider makes it so that the user only has to declare the dropdown once (instead of on every screen they want to use it). To call the methods like `alertWithType` they use the connectDropdownAlert function/decorator that gives their component access to the dropdown's methods via props. `this.props.alert('Custom', 'custom text');`

Here's my root component for my app:
```
 render() {
    const route = this.state.loggedIn ? 'tabs' : 'onboarding';

    return (
      <Choose>
        <When condition={ this.state.loading }>
          <Components.AppLoading />
        </When>
        <Otherwise>
          <DropdownAlertProvider>
            <ActionSheetProvider>
              <NavigationProvider router={ Router }>
                <StackNavigation id="master" initialRoute={ Router.getRoute(route) } />
              </NavigationProvider>
            </ActionSheetProvider>
          </DropdownAlertProvider>
        </Otherwise>
      </Choose>
    );
```

and in other screens I can do this:

```
@connectDropdownAlert
export default class NewComp extends Component {
  componentDidMount() {
    this.props.alertWithType('error', 'Error', 'JK this really isn\'t an error');
  }

  render() {
    return <View style={{ flex: 1 }} />;
  }
}
```

Nowhere do I have to explicitly import the dropdown component or attach the ref and It makes it easier to use and reduce code duplication

**Comment by fmr** [comment]
@datwheat Thanks for providing that gist and example. I'm also new to HOC, and I like the approach you took because like you, I thought it seemed unnecessary to import and set up the component on every scene.

I used the same `DropdownAlertProvider` class and `connectDropdownAlert` function you provided in your gist. I followed your instructions above, and couldn't quite get it to work.

The problem I'm having is this:

![image](https://cloud.githubusercontent.com/assets/592174/22635324/c38d1084-ec86-11e6-8955-39fc1fb734a1.png)

It seems like calling `this.props.alertWithType` from a child component doesn't work - even the props have successfully been passed through. The problem is when `DropdownAlertProvider::getChildContext` is called, `this.dropdown` does not exist. Would you have an idea of why `this.dropdown` would not be set?

**Comment by datwheat** [comment]
@fmr I just updated the gist, copy/pasted from what I have in my codebase. It should work as long as you `npm i -S hoist-non-react-statics react-native-dropdownalert`, wrap your RootComponent in the Provider, and for any screen you want to call those methods on, either use the decorator syntax `@connectDropdownAlert` or call the function with the screen/component inside it `export default connectDropdownAlert(Component)`

**Comment by fmr** [comment]
@datwheat, thank you for that. I also thought that it could've been a dependency issue, but I already had `hoist-non-react-statics` and `react-native-dropdownalert` installed when I checked. 

I did get it to work eventually, after a bit of fiddling - and for the particular issue I described, I was trying to access `this.props.alertWithType` from `componentDidMount` or `componentWillMount`. As soon as I moved it to an onClick handler method, it ended up working. I didn't dig deeper to figure out why that was.

The other thing worth mentioning is that I believe decorators aren't supported by default, and might require some extra setup - at least as of Babel 6. I don't know which plugin to use, so I ended up using this syntax, as you described:

```javascript
export default connectDropdownAlert(Component)
```

That said, I still think what you have is a good approach. If you have a small sample repo where this approach is used, it'll be easier to show how everything ties together. I would also love to be able to see how you would use this in a redux setup, but now I'm just being greedy :)

**Comment by devBrian** [comment]
Hi @fmr and @datwheat  I am curious as well on a redux / HOC approach example. I do like this approach. Would anything need to be exposed or changed to this module itself to help support this easier? Thanks.

**Comment by datwheat** [comment]
AFAIK to use it with redux you have to make Dropdown.alert* a static method that you can call outside of react or somehow be able to pass the alert* function props into your reducers

**Comment by datwheat** [comment]
GMT that's because the drop-down hasn't mounted yet in componentWillMount, but I'm not sure what's up with componentDidMount

**Comment by fmr** [comment]
@datwheat thanks for the feedback. You're right, it makes sense that it doesn't work in `componentWillMount`, but not in `componentDidMount` - but I'm not too concerned now that I've got everything kind of working :)

----

@devBrian it'll be much simpler to integrate in redux if you only need to update the component's props.

So, if all it takes to show an alert is this:

```jsx
<DropdownAlert visible={true} alertType="info" message="Hello world!" />
```

And to hide:
```jsx
<DropdownAlert visible={false} alertType="info" message="Hello world!" />
```

Then, all you need to do within the `render` method of your connected redux component will be something like:

```jsx
const { message } = this.props; // props defined in mapStateToProps
const visible = !!message;

return (
...
  <DropdownAlert visible={visible} alertType="info" message={message} />
);
```
I was trying to wrap `DropdownAlert` in another component so I can do this, but because of the extra setup involved, I haven't been able to have much success with it.

@devBrian, I found another project that uses this approach, if you're interested:

https://github.com/gnestor/react-native-statusbar-alert

Anyway, keep up the good work!

**Comment by maguon** [comment]
It is important to support redux.The component should be have props to control visible and message.

**Comment by datwheat** [comment]
@maguon @fmr although props would be nice, props are not needed for redux. All you have to do is in componentWillUpdate(nextProps) {} call the alert function with your message in nextProps.message

**Comment by datwheat** [comment]
This is by no means a 'small' demo and it doesn't use redux (i use MobX + component state), but here's my app that uses my HOC setup in various scenarios https://github.com/datwheat/pul

**Comment by sibelius** [comment]
@datwheat you should send a PR adding this

@testshallpass providers is very common, check this for instance: https://github.com/expo/react-native-action-sheet

**Comment by datwheat** [comment]
@testshallpass do you think a PR for my provider API would be worthwhile?

**Comment by testshallpass** [comment]
@datwheat I always welcome PRs. So are you speaking about the gist you shared? My plan is to follow @fmr suggestions but doing so will make this a major release.

**Comment by datwheat** [comment]
I agree with following @fmr's prop-controlled alerts. And then on top of that I can provide a Provider implementation that operates with the new props api

**Comment by testshallpass** [comment]
Hi @datwheat Check out branch: change-visibility-mechanism. It is close to done, let me know what you think.

**Comment by testshallpass** [comment]
Hi @fmr I finish a change to visibility of DropdownAlert. So like your example you can show/hide like so: 

```javascript
 <DropdownAlert 
    visible={this.state.visible}
    type={this.state.type}
    title={this.state.title}
    message={this.state.message} />
```
For more info, check out PR #55

**Comment by 0x6e6562** [comment]
Similar to @fmr https://github.com/testshallpass/react-native-dropdownalert/issues/30#issuecomment-277887269 I also ran into the

`Cannot read property 'alertWithType' of undefined`

error after trying to implement an AlertProvider (inspiration taken from @spencercarli https://github.com/spencercarli/ex-navigation-to-react-navigation/blob/replace-alert/app/components/Alert/AlertProvider.js).

Turns out that when I first tested the integration, I tried to invoke `alertWithType` in the `render` function of my root component before any error object had been created. I guess that `alertWithType` is not available until the component creation/wrapping lifecycle has completed?

**Comment by testshallpass** [comment]
So the component is not rendered until the `isOpen` state is true this is when `alertWithType` invoked. Would PR #55 help?

**Comment by 0x6e6562** [comment]
It is a bit difficult to read #55 because the patch contains a lot of churn - it feels like a significant refactoring of the library. What I glean from the changeset in #55 is that a flag has been introduced so that injected components can know when the alerting infrastructure has been initialized and is ready to accept requests to render alerts.

But I might be wrong, seeing as the PR doesn't have a description (I believe most of the description about it are in comments in other issue threads).

If it is about knowing when the `AlertProvider` is ready to be invoked, then yes, I think that #55 could be a cleaner way to know the state of the component lifecycle. Currently I am relying on the assumption that the alerting is ready, due to the way that I seen it behave in practice. Having an explicit mechanism would remove the need to make assumptions about the state.
