### ISSUE TITLE
Change closeInterval

### ISSUE THREAD

**Issue by marcosinigaglia** [testshallpass/react-native-dropdownalert#36]
Is possibile to change the closeInterval during the alert call?

**Comment by testshallpass** [comment]
I don't think so, as I would imagine I need to use `componentWillReceiveProps()` and detect a change there. Have you tried doing a state change on closeInterval after you invoke it?

**Comment by marcosinigaglia** [comment]
I tried but I changed it before the alert call, if is an useful feature I'll try to add a method `alertWithCloseInterval` and make a PR.

**Comment by testshallpass** [comment]
What's your use case? I don't think another method is needed but perhaps expand on the alertWithType params.

**Comment by marcosinigaglia** [comment]
In my case I have a unique DropdownAlert in the app, in the most case I use a closeInterval but in one case I need to set closeInterval to 0. I can add another DropdownAlert and use it.

**Comment by testshallpass** [comment]
I think I need to implement `componentWillReceiveProps()`and detect changes of the props since the alert is mounted. I need to do some testing to make sure. Other than that, yeah add another for now. I may add closeInterval as a param as well. So a couple things to try out and I will get back to you.

**Comment by marcosinigaglia** [comment]
Thanks!

**Comment by maartenvandillen** [comment]
any news on this? an extra param to alertWithType would be a nice addition
